terraform-aws-modules/terraform-aws-iam

modules/iam-account/main.tf, modules/iam-account/variables.tf
Hi,
I wanted to set the password age with the module but couldn't find the required variable.
This is possible with terraform [aws_iam_account_password_policy](https://www.terraform.io/docs/providers/aws/r/iam_account_password_policy.html#max_password_age) ressource.
=> Add max_password_age for password policy

modules/iam-assumable-roles/variables.tf
There seems to have been a copypasta error in a `variables.tf` file. This change makes the descriptions consistent with the variables.
=> fix descriptions of variables

modules/iam-user/README.md, modules/iam-user/main.tf, modules/iam-user/outputs.tf, modules/iam-user/variables.tf
=> Ssh key support 

modules/iam-user/variables.tf
The variable tags is duplicated and Terragrunt is failing
```
Error: Duplicate variable declaration
on .terraform/modules/iam_user/terraform-aws-modules-terraform-aws-iam-c736c90/modules/iam-user/variables.tf line 84:
84: variable "tags" {
```
=> Variable duplication

README.md
iam-assumable-role example link was pointing to iam-assumable-roles example. This PR fixes that link.
=> Fix link to iam-assumable-role example in README

modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/variables.tf
Adds a new feature that allows for the addition of AWS Service Principals. Specifics on AWS Role Principals can be found here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html
=> Add Trusted Services to iam-assumable-role

modules/iam-group-with-policies/main.tf
I got into a limitation regarding set descriptions for roles used inside `iam-group-with-policies` module. 
I added the possibility of set descriptions for roles using a terraform `lookup` function, which doesn't affect the behaviour because it sets to `null` description (basically not set) in case user doesn't specify description field inside the lits(maps)
=> Added description for roles when using iam-group-with-policies

modules/iam-assumable-role/main.tf, modules/iam-assumable-role/variables.tf
This PR adds support for custom description in iam-assumable-role. It can be useful in cases where services depend on role description (like keymaker for example).
This is based on https://github.com/terraform-aws-modules/terraform-aws-iam/issues/40
=> iam-assumable-role: add description support

CHANGELOG.md, examples/iam-group-with-assumable-roles-policy/README.md, modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/outputs.tf, modules/iam-assumable-role/variables.tf
I added the possibility to create an IAM instance profile to "iam-assumable-role" As it only takes 1 extra parameter, and is whitin the scope of this module (IAM)
=> add instance profile to iam-assumable-role

examples/iam-account/README.md, examples/iam-assumable-role-with-oidc/README.md, examples/iam-assumable-role/README.md, examples/iam-assumable-roles-with-saml/README.md, examples/iam-assumable-roles/README.md, examples/iam-group-complete/README.md, examples/iam-group-with-assumable-roles-policy/README.md, examples/iam-group-with-policies/README.md, examples/iam-policy/README.md, examples/iam-user/README.md, modules/iam-account/README.md, modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role/README.md, modules/iam-assumable-roles-with-saml/README.md, modules/iam-assumable-roles/README.md, modules/iam-group-with-assumable-roles-policy/README.md, modules/iam-group-with-policies/README.md, modules/iam-policy/README.md, modules/iam-user/README.md, modules/iam-user/variables.tf
The pgp_key is only required if `create_iam_login_profile` is set. This should be reflected in README. It addresses the issue #39.
Documentation is somehow misleading
No
=> docs: Add note about pgp_key when create_iam_login_profile is set

modules/iam-user/README.md, modules/iam-user/outputs.tf, modules/iam-user/versions.tf
This PR changes output value of `this_iam_access_key_ses_smtp_password` in `iam-user` submodule from deprecated attribute ` ses_smtp_password` to new one `ses_smtp_password_v4`, referencing secret access key converted into an SES SMTP password by applying AWS's documented Sigv4 conversion algorithm.
The SES SMTP interface no longer supports legacy AWS's SigV2 conversion algorithm and only works with Sigv4:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html
The change was introduced in AWS provider version `2.50`.
https://www.terraform.io/docs/providers/aws/r/iam_access_key.html#ses_smtp_password_v4
terraform-providers/terraform-provider-aws#11143
terraform-providers/terraform-provider-aws#11144
Since the old SigV2 signed passwords no longer work for AWS SES SMTP …
=> feat: modules/iam-user - Output SMTP password generated with SigV4 algorithm

modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/variables.tf
Add var to action to can fill out in module iam-assumable-role
We use github actions and the AWS action to get credentials need the sts:TagSession permission as you can read on:
https://github.com/aws-actions/configure-aws-credentials/
Doesn't apply
I tested this changes on my AWS account to ensure that works as I spected
=> fix: Allow customisation of trusted_role_actions in iam-assumable-role module

modules/iam-user/README.md, modules/iam-user/outputs.tf
`iam-user`'s output ses_smtp_password is cannot access error.
```zsh
Error: Unsupported attribute
on .terraform/modules/iam_user_test/modules/iam-user/outputs.tf line 63, in output "this_iam_access_key_ses_smtp_password":
63:       aws_iam_access_key.this.*.ses_smtp_password,
This object does not have an attribute named "ses_smtp_password".
```
Cannot create iam-user.
=> fix: Delete DEPRECATED ses_smtp_password in iam-user.

examples/iam-assumable-role/main.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/outputs.tf, modules/iam-assumable-role/variables.tf
- Add support of sts:ExternalId
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html - sometimes service integration require ExternalId instead of MFA.
None
I've tested in my environment having this kind of setup:
```
module "iam_assume_role_in_prod_testrole" {
source = "git::https://github.com/LAKostis/terraform-aws-iam.git//modules/iam-assumable-role?ref=feature/add-sts-externalid-support"
trusted_role_arns = [
"arn:aws:iam::${var.some_account_id}:root",
]
create_role = true
role_name         = "DatadogAWSIntegrationRole"
role_requires_mfa = false
sts_externalid = var.datadog_sts_id
custom_role_policy_arns = [
"arn:aws:iam::${data.aws_caller_identity.test.account_id}:policy/DatadogAWSIntegrationPolicy",
]
providers = {
aws = aws.test
}
}
```
=> feature: add sts:ExternalId

modules/iam-assumable-role-with-oidc/main.tf
by using the current partition instead of hardcoding "aws"
Currently this module does not work in govcloud because it hardcodes "arn:aws:...", while govcloud uses ARNs of the form "arn:aws-gov". This changes to use the documented technique for getting the current partition.
None.
I have verified in a local Xometry environment that this produces correct and working IAM role definitions for both govcloud and non-govcloud environments.
=> fix: Allow modules/iam-assumable-role-with-oidc to work in govcloud

modules/iam-assumable-role-with-oidc/main.tf
The OIDC URL returned from the AWS API and https://github.com/terraform-aws-modules/terraform-aws-eks
contains the https:// scheme in the URL, this handles removing it
automatically, as required for correctly creating IAM policies.
=> feat: Strip https:// from OIDC provider URL if present

modules/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role/main.tf, modules/iam-group-with-policies/main.tf
Simplify Count statement in 2 cases of policy attachments as it causes failures during apply in some cases
Simplify Count statement in 2 cases of policy attachments as it causes failures during apply in some cases
No.
Yes.
=> fix: simplify count statements

modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role-with-oidc/variables.tf
Add "role_description" variable for the "assumable-role-with-oidc" module
During a personal project using this excellent module I noticed that the feature to add a description for an oidc role was missing.
Nothing breaks, the change is minor. The parts that were added were copy-pasted from the "assumable-role" module.
The change in the module was tested against a role that had no description before and one was added via this branch, and then the description was changed through the same method. No issues detected.
=> feat: Add role description variable for assumable role with oidc

.pre-commit-config.yaml
Needed with new terraform-docs
Update to latest `pre-commit-terraform` release
The old pre-commit-terraform was failing to update README.md with a new install and new terraform-docs (`0.10.1`). This was stopping me from making a functional PR
No known breaking changes
Run locally
=> ci: Update pre-commit-terraform

examples/iam-assumable-roles-with-saml/main.tf, modules/iam-assumable-roles-with-saml/README.md, modules/iam-assumable-roles-with-saml/main.tf, modules/iam-assumable-roles-with-saml/variables.tf
The aws_iam_policy_document has support for specifying multiple principle federated identifiers like this:
```
"Principal": {
"Federated": [
"arn:aws:iam::012345678912:saml-provider/first",
"arn:aws:iam::012345678912:saml-provider/second"
]
},
```
Currently, this module only supports specifying one provider_id:
```
principals {
type        = "Federated"
identifiers = [var.provider_id]
}
```
Solves issue #109 
-
Not yet tested
=> iam-assumable-roles-with-saml: Allow for multiple provider ids

.gitignore, examples/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role-with-oidc/variables.tf
Changed to automatically calculate `number_of_role_policy_arns` even if you omit this.
Added backward compatibility to #116
By default the `number_of_role_policy_arns` should be calculated automatically, but it can be also specified explicitly as variable.
Probably not
Use new example.
=> fix: automatically determine the number of role policy arns

modules/iam-assumable-role-with-oidc/main.tf
fix #114 
See #114 
No breaking changes
This PR was tested by extending the example provided with the module (examples/iam-assumable-role-with-oidc).
Also see **expected output** in #114
```
+ resource "aws_iam_role" "this" {
+ arn                   = (known after apply)
+ assume_role_policy    = jsonencode(
{
+ Statement = [
+ {
+ Action    = "sts:AssumeRoleWithWebIdentity"
+ Condition = {
+ StringEquals = {
+ oidc.eks.eu-west-1.amazonaws.com/id/AA9E170D464AF7B92084EF72A69B9DC8:sub = [
+ "system:serviceaccount:default:sa2",
+ "system:serviceaccount:default:sa1",
]
}
}
+ Effect    = "Allow"
+ Principal = {
+ Federated = "arn:aws:iam::530488130478:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/AA9E170D464AF7B92084EF72A69B9DC8"
}
+ Sid       = ""
},
+ {
+ Action    = …
```
=> fix: Multiple provider_urls not working with iam-assumable-role-with-oidc

modules/iam-group-with-assumable-roles-policy/README.md, modules/iam-group-with-assumable-roles-policy/outputs.tf
Export arn of created groups
We have multiple AWS accounts across our org. IAM user are kept centrally in one account, are put into groups and the groups get permission to `assumeRole` in other accounts. We need the group arn for the trustee relationship between the accounts.
I run Terraform from my branch and compared the result.
Before:
```
Unsupported attribute
on outputs.tf line 5, in output "groups":
5:       arn   = module.iam-groups[name]. group_arn
|----------------
| module.iam-groups is object with 3 attributes
This object does not have an attribute named "group_arn".
```
After:
```
Changes to Outputs:
+ groups = [
+ {
+ arn  = (known after apply)
+ name = "data-services-admin"
},
+ {
+ arn  = (known after apply)
+ name = "data-services-developer"
},
+ {
+ arn  = (known after …
```
=> feat: Add arn of created group(s) to outputs

.gitignore, .pre-commit-config.yaml, examples/iam-account/README.md, examples/iam-assumable-role-with-oidc/README.md, examples/iam-assumable-role/README.md, examples/iam-assumable-roles-with-saml/README.md, examples/iam-assumable-roles/README.md, examples/iam-group-complete/README.md, examples/iam-group-with-assumable-roles-policy/README.md, examples/iam-group-with-policies/README.md, examples/iam-policy/README.md, examples/iam-user/README.md, modules/iam-account/README.md, modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role/README.md, modules/iam-assumable-roles-with-saml/README.md, modules/iam-assumable-roles/README.md, modules/iam-group-with-assumable-roles-policy/README.md, modules/iam-group-with-policies/README.md, modules/iam-policy/README.md, modules/iam-user/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
=> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
- update ci-cd workflow to allow for pulling min version from each directory
- update to workflow to allow modules/examples use different min terraform versions
- no
- ci-cd static checks
=> chore: update ci-cd workflow to allow for pulling min version from each directory

modules/iam-user/outputs.tf
There are use cases when encryption is not possible and these are not handled properly right now.
Sometimes internal accounts are created and they never leave Terraform and encryption is not possible due to the lack of decryption functionality within Terraform.
When not appropriate, Keybase commands will just be null, which could be extended further to check if a regular PGP key is used and not a Keybase one.
=> fix: handle unencrypted secrets

README.md, examples/iam-assumable-role-with-saml/README.md, examples/iam-assumable-role-with-saml/main.tf, examples/iam-assumable-role-with-saml/outputs.tf, examples/iam-assumable-role-with-saml/saml-metadata.xml, examples/iam-assumable-role-with-saml/versions.tf, modules/iam-assumable-role-with-saml/README.md, modules/iam-assumable-role-with-saml/main.tf, modules/iam-assumable-role-with-saml/outputs.tf, modules/iam-assumable-role-with-saml/variables.tf, modules/iam-assumable-role-with-saml/versions.tf
This PR adds an `iam-assumable-role-with-saml` module to add individual SAML assumed roles based on the similar `iam-assumable-role-with-oidc` module.
The `iam-assumable-roles-with-saml` module is handy but only allows you to create the three predefined roles. I need to be able create many additional roles with arbitrary policies attached.
Fixes #126
No
I've applied the example code to a test account.
=> feat: Add iam-assumable-role-with-saml module

examples/iam-assumable-role/README.md, examples/iam-assumable-role/main.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/outputs.tf, modules/iam-assumable-role/variables.tf
Allows more than one STS External ID to be provided to an assumable role.
We need to pass multiple External IDs allowing one role for multiple external ids.
No
I have added the `role_sts_external_ids` field to the `iam-assumable-role` example.
```
+ resource "aws_iam_role" "this" {
+ arn                   = (known after apply)
+ assume_role_policy    = jsonencode(
{
+ Statement = [
+ {
+ Action    = "sts:AssumeRole"
+ Condition = {
+ StringEquals = {
+ sts:ExternalId = [
+ "some-id-goes-here",
]
}
}
+ Effect    = "Allow"
+ Principal = {
+ AWS     = "arn:aws:iam::307990089504:root"
+ Service = "codedeploy.amazonaws.com"
}
+ Sid       = ""
},
]
+ Version   = "2012-10-17"
}
)
+ create_date           = (known after apply)
+ force_detach_policies = false
+ id                    = (known after …
```
=> feat: Allows multiple STS External IDs to be provided to an assumable role

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, examples/iam-account/README.md, examples/iam-assumable-role-with-oidc/README.md, examples/iam-assumable-role-with-saml/README.md, examples/iam-assumable-role/README.md, examples/iam-assumable-roles-with-saml/README.md, examples/iam-assumable-roles/README.md, examples/iam-group-complete/README.md, examples/iam-group-with-assumable-roles-policy/README.md, examples/iam-group-with-policies/README.md, examples/iam-policy/README.md, examples/iam-user/README.md, modules/iam-account/README.md, modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role-with-saml/README.md, modules/iam-assumable-role/README.md, modules/iam-assumable-roles-with-saml/README.md, modules/iam-assumable-roles/README.md, modules/iam-group-with-assumable-roles-policy/README.md, modules/iam-group-with-policies/README.md, modules/iam-policy/README.md, modules/iam-user/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
=> chore: update documentation and pin `terraform_docs` version to avoid future changes

.github/workflows/pre-commit.yml, modules/iam-assumable-role/README.md, modules/iam-assumable-role/outputs.tf
Adds a new output (`iam role unique-id`) to module `iam-assumable-role`
We are using HashiCorp Vault version 1.2 and at this version, the only metadata we have to craft policies is the IAM Role Unique ID.
None
=> feat: Add role unique_id output in iam-assumable-role module

examples/iam-assumable-role-with-oidc/README.md, examples/iam-assumable-role-with-oidc/outputs.tf, examples/iam-assumable-role-with-saml/README.md, examples/iam-assumable-role-with-saml/outputs.tf, examples/iam-assumable-role/README.md, examples/iam-assumable-role/outputs.tf, examples/iam-assumable-roles-with-saml/README.md, examples/iam-assumable-roles-with-saml/outputs.tf, examples/iam-assumable-roles/README.md, examples/iam-assumable-roles/outputs.tf, modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role-with-oidc/outputs.tf, modules/iam-assumable-role-with-saml/README.md, modules/iam-assumable-role-with-saml/outputs.tf, modules/iam-assumable-roles-with-saml/README.md, modules/iam-assumable-roles-with-saml/outputs.tf, modules/iam-assumable-roles/README.md, modules/iam-assumable-roles/outputs.tf
Adds unique_id from aws_iam_role to outputs.
Resolves #141. The unique_id is required in certain AWS contexts, so it is a needed output.
No breaking changes.
Deployed module from personal fork and verified that unique_ids are present in the output.
=> feat: Add iam role unique_id to outputs

examples/iam-policy/main.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/versions.tf, modules/iam-group-with-assumable-roles-policy/README.md, modules/iam-group-with-assumable-roles-policy/main.tf, modules/iam-group-with-assumable-roles-policy/variables.tf, modules/iam-group-with-policies/README.md, modules/iam-group-with-policies/main.tf, modules/iam-group-with-policies/variables.tf, modules/iam-policy/README.md, modules/iam-policy/main.tf, modules/iam-policy/variables.tf, modules/iam-policy/versions.tf, modules/iam-user/main.tf
Add `tags` variable:
`aws_iam_instance_profile` [released in TerraformAWS provider v3.34](https://github.com/hashicorp/terraform-provider-aws/blob/v3.34.0/CHANGELOG.md) on PR [#17962](https://github.com/hashicorp/terraform-provider-aws/pull/17962)
`aws_iam_policy` [released in terraform-aws-provider v3.35](https://github.com/hashicorp/terraform-provider-aws/blob/v3.35.0/CHANGELOG.md) on PR [#18276](https://github.com/hashicorp/terraform-provider-aws/pull/18276)
I need to tag all (or at least I would like that) resources provisioned, Its help me with cost management and organization
=> feat: Add support tags to additional IAM modules

modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role-with-oidc/variables.tf
This adds support for cross-account assumable role with OIDC
We have a use-case where a EKS service account in an account should be able to assume a role in a EKS cluster in another account.
Fixes https://github.com/terraform-aws-modules/terraform-aws-iam/issues/157
It doesn't bring a breaking change.
In my environment, the module `iam-assumable-role-with-oidc` is used as a submodule in our custom irsa terraform module. 
I created a new irsa module, calling my updated `terraform-aws-iam//modules/iam-assumable-role-with-oidc`.
As a variable, I've set `oidc_fully_qualified_audience` to `sts.amazonaws.com` and then ran `tf apply`
Below the relevant part of it:
```  
+ resource "aws_iam_role" "this" {
+ arn                   = (known after apply)
+ assume_role_policy    = jsonencode(
{
+ …
```
=> feat: Cross-account in iam-assumable-role-with-oidc

README.md
Update version constraints to prevent from (theoretical) problems when copy pasting examples...
Someone (!) could copy paste and have errors difficult to interpret:
```
│ Error: Unsupported attribute
│
│   on roles.tf line 186, in module "iam_group_with_assumable_roles_policy":
│  186:     module.iam_assumable_role_custom.iam_role_arn
│     ├────────────────
│     │ module.iam_assumable_role_custom is a object, known only after apply
│
│ This object does not have an attribute named "iam_role_arn".
``` 
None
Copy pasted and it worked. :)
=> docs: Update version constraints

examples/iam-policy/README.md, examples/iam-policy/main.tf, modules/iam-policy/README.md, modules/iam-policy/main.tf, modules/iam-policy/outputs.tf, modules/iam-policy/variables.tf
Add ability for controlling whether or not to create a policy
In certain scenarios can be useful to decide which specific policy should be created or not. Let's imagine that we create a module from this module for creating a set of policies that might change depending on the account you are targeting. This change allows you to do that.
There is no breaking change as the module still behaving the same by default.
- [✅] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [✅] Tested over my own AWS account.
=> feat: Add ability for controlling whether or not to create a policy

examples/iam-assumable-role/README.md, examples/iam-assumable-role/main.tf, examples/iam-assumable-role/outputs.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/outputs.tf
Added the IAM Instance Profiles ID to the `iam-assumanle-role` exported output.
I was unable to add the IAM instance profiles `ID` attribute when trying to add `iam_instance_profile` to an EC2 Terraform Resource using the `iam-assumanle-role` module.
None
_Testing_
I add the ID attribute to the outputs and locally tested the module's example template with Terraform version 1.x and provider
version v.3.58.0
Terraform apply output showing the IAM Instance Profile ID below:
````
Outputs:
iam_instance_profile_id = "admin"
iam_role_arn = "arn:aws:iam::185203724531:role/admin"
iam_role_name = "admin"
iam_role_path = "/"
iam_role_unique_id = "AROASWHYASDZ4CRLPZFCH"
role_requires_mfa = true
```
=> feat: Added id of iam assumable role to outputs

examples/iam-group-with-policies/README.md, examples/iam-group-with-policies/outputs.tf, modules/iam-group-with-policies/README.md, modules/iam-group-with-policies/outputs.tf
Add `group_arn` to the outputs of the `iam-group-with-policies` module.
I was missing this feature for a personal project, where I am using the `iam-assumable-roles` module and want to refer to a group by its ARN.
No breaking changes, just adding a new output.
I have tested this change on my aforementioned project. The output is there and I can refer to it in other resources.
=> feat: iam-group-with-policies output group_arn

README.md, examples/iam-eks-role/README.md, examples/iam-eks-role/main.tf, examples/iam-eks-role/outputs.tf, examples/iam-eks-role/versions.tf, modules/iam-assumable-role-with-oidc/variables.tf, modules/iam-eks-role/README.md, modules/iam-eks-role/data.tf, modules/iam-eks-role/main.tf, modules/iam-eks-role/outputs.tf, modules/iam-eks-role/variables.tf, modules/iam-eks-role/versions.tf
Adding a new, user-friendly module that is specifically for AWS EKS users.
Currently EKS users would use the module `iam-assumable-role-with-oidc` but the way it is structured/implemented is quite confusing:
1. You have to deal with or know your cluster OIDC URL
2. Can't create a role that is assumable by multiple `ServiceAccount` per multiple clusters as `provider_urls` and `oidc_fully_qualified_subjects` are separate.
3. Most EKS users don't know what `oidc_fully_qualified_subjects` are and shouldn't need to.
4. It still needs to be wrapped in another module or requires a `data` resource to get the OIDC URL of each cluster
This module solves these in a nice clean way for EKS users by using a data resource inside the module and having a one-to-many relationship from `provider_url` to …
=> feat: Add new IAM module iam-eks-role

examples/iam-assumable-role/README.md, examples/iam-assumable-role/main.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/variables.tf
This change adds an option to set a custom trust policy.
I need to create an assumable role that can be assumed from all member accounts of the organization except for sandbox accounts.
This can be achieved via conditions and a deny policy for the sandbox.
As there is no possibility to cover all options of the JSON policy, the best would be for such rare situations to allow a custom trust policy.
=> feat: Allow setting custom trust policy in iam-assumable-role

modules/iam-read-only-policy/README.md, modules/iam-read-only-policy/variables.tf
Added Cost Explorer to default console services defaults.
AWS updated home screen and now it shows data from cost explorer thus generating Cloud Trail accessed denied events if policy does not container Cost Explorer
N/A
Plus local tests
=> feat: Include cost explorer to default console services in `iam-read-only-policy` module

modules/iam-role-for-service-accounts-eks/policies.tf
- Correct permission on AWS load balancer controller; looks like it was a copy past error https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/694a0b14184e388806f9f34be0dd9075aa8fb0a7/docs/install/iam_policy.json#L216
- Closes #190 
- No
=> fix: Correct permission on AWS load balancer controller

modules/iam-role-for-service-accounts-eks/policies.tf
cluster-autoscaler >=[v1.23.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.23.0) requires an extra IAM permission - ec2:DescribeInstanceTypes
The merging of https://github.com/kubernetes/autoscaler/pull/4468 means that the default configuration of the CA will now require an extra IAM permission - `ec2:DescribeInstanceTypes`
No breaking change.
=> fix: Add ec2:DescribeInstanceTypes permission for Kubernetes Autoscaler 1.23.0

modules/iam-assumable-role/README.md, modules/iam-assumable-role/variables.tf
Corrects a typo in the variable description for `var.custom_role_trust_policy`.
Noticed while reviewing docs.
No.
N/A
=> docs: Fixed a typo in `var.custom_role_trust_policy` description

modules/iam-role-for-service-accounts-eks/policies.tf
- Trigger release for adding `ec2:DescribeInstanceTypes` patched in #192; simple comma "no-op" additions were added to ensure change set triggers release workflow
- The title was malformed in #192 which means that the release process was not executed properly (ignored). This is just a simple no-op process to trigger a release for that change
- Closes #195
- No
=> fix: Trigger release for adding `ec2:DescribeInstanceTypes` patched in #192

modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/variables.tf
- Add variable to change IAM condition test operator to suite; defaults to `StringEquals`
- Correct parameter name usage in `README.md` (`service_accounts` -> `namespace_service_accounts`) to be correct
- Closes #198
- Closes #200
- No
=> feat: Add variable to change IAM condition test operator to suite; defaults to `StringEquals`

modules/iam-role-for-service-accounts-eks/policies.tf
Fixed a typo  causing plan/apply to fail when `ebs_csi_kms_cmk_ids` is set in the `"terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"` module.
Without this change, setting `ebs_csi_kms_cmk_ids` results in the following error (`statement.value` is `1` instead of the list of CMK ARNs):
```
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/[redacted].aws_ebs_csi_driver_irsa/modules/iam-role-for-service-accounts-eks/policies.tf line 259, in data "aws_iam_policy_document" "ebs_csi":
│  259:       resources = statement.value
│ 
│ Inappropriate value for attribute "resources": set of string required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/[redacted].aws_ebs_csi_driver_irsa/modules/iam-role-for-service-accounts-eks/poli …
```
=> fix: Policy generation when `ebs_csi_kms_cmk_ids` is set

modules/iam-user/README.md, modules/iam-user/outputs.tf, modules/iam-user/variables.tf, modules/iam-user/versions.tf
This will make the `pgp_key` argument optional in all configurations and add the unencrypted user password to the list of outputs. This will also raise the minimum required `aws` provider version to `4.1.0`
When trying to create an iam user without a `pgp_key` but with an `iam_user_login_profile` the creation would fail.
Since version `4.1.0` of the `aws` provider the `pgp_key` argument of the resource `aws_iam_user_login_profile` is **optional**. Thus the constraint that a `pgp_key` is required when using `create_iam_user_login_profile = true` is not needed anymore.
👉 [Terraform docs for `aws_iam_user_login_profile` (`4.1.0`)](https://registry.terraform.io/providers/hashicorp/aws/4.1.0/docs/resources/iam_user_login_profile)
No
=> feat: Make PGP Key Optional in All Cases

modules/iam-user/README.md, modules/iam-user/versions.tf
Revert AWS provider version requirement for recent release, in order to prevent something like the following error out of a `terraform init`:
```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/aws:
│ no available releases match the given constraints >= 2.45.0, ~> 3.0, < 4.0.0,
│ >= 4.1.0
```
Not break compatibility in workspaces that still couldn't upgrade their AWS provider -- but probably should eventually.
The opposite, actually.
`terraform init` working again.
=> fix: Backwards compatibility in 4.x.x series in iam-user submodule

.pre-commit-config.yaml, examples/iam-role-for-service-accounts-eks/README.md, examples/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/policies.tf, modules/iam-role-for-service-accounts-eks/variables.tf
- Add support for EFS CSI driver to `iam-role-for-service-accounts-eks`
- Allow users to use EFS CSI driver using IRSA role
- No
=> feat: Add support for EFS CSI driver to `iam-role-for-service-accounts-eks`

examples/iam-role-for-service-accounts-eks/README.md, examples/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/policies.tf, modules/iam-role-for-service-accounts-eks/variables.tf
- Add support for:
- AWS Managed Service for Prometheus
- Cert-Manager
- External-Secrets
- FSx for Lustre CSI Driver
- Additional addons that are commonly used/requested
- Closes #204
- Closes #206
- Closes #217
- Closes #221
- Closes #222
- No
=> feat: Add support for AMP, cert-manager, and external-secrets to `iam-role-for-service-accounts-eks`

examples/iam-role-for-service-accounts-eks/main.tf
The [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html) uses a service account name `aws-node` instead of `aws-vpc-cni`, the Helm chart name.
Don't want someone to be misled by current documentation.
None
I've successfully used `aws-node` in my projects and was forced to double-check the AWS documentation after seeing the example here.
=> fix: Fixed example where VPC CNI permissions should apply to the `aws-node` account

modules/iam-role-for-service-accounts-eks/README.md
- karpenter_controller_cluster_ids changed to karpenter_controller_cluster_id, but the README sample did not change, so I fixed it.
- https://github.com/terraform-aws-modules/terraform-aws-iam/pull/209 Thie
=> chore: Fixed README karpenter_controller_cluster_ids parameter

modules/iam-role-for-service-accounts-eks/policies.tf
Fixes permissions for the AWS EFS CSI Driver IRSA.
Necessary permissions for operation are omitted per the reference policy: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json
N/A
=> fix: Add necessary permissions to EFS IRSA policy

examples/iam-role-for-service-accounts-eks/main.tf
The example attaches the wrong policy.
=> fix: Correct policy attachment to cert_manager in example

examples/iam-role-for-service-accounts-eks/README.md, examples/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/policies.tf, modules/iam-role-for-service-accounts-eks/variables.tf
- Added appmesh controller support to `iam-role-for-service-accounts-eks`
- Allow users to use Appmesh controller  using IRSA role
- None
=> feat: Added appmesh controller support to `iam-role-for-service-accounts-eks`

modules/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/policies.tf
This is a revised version of MR [229](https://github.com/terraform-aws-modules/terraform-aws-iam/pull/229)
It will fix all hardcoded arn to be partition targeted.
Closes #226
N/A
- [*] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
I have successfully launched Karpenter on "aws-cn" partiton.
I will also create another MR for Karpenter examples in terraform-aws-modules.
=> fix: Correct aws arn partition for service account eks

modules/iam-role-for-service-accounts-eks/policies.tf
- fixed invalid iam policy for app mesh controller.
- https://github.com/terraform-aws-modules/terraform-aws-iam/pull/231#discussion_r856940564
- Fixed invalid policy
- none
=> fix: Correct invalid policy for app mesh controller

modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/policies.tf, modules/iam-role-for-service-accounts-eks/variables.tf
Replace `AmazonEKS_` with user provided variable `policy_name_prefix` which defaults to `AmazonEKS_`
Many organizations have specific naming convention requirements for roles and policies. Allowing for name prefixes means members of those organizations can utilize this module and be compliant. 
Closes #239 
No breaking changes.
=> feat: Add `policy_name_prefix` for IRSA policies

examples/iam-role-for-service-accounts-eks/main.tf
Changed the name of the service account from `aws-ebs-csi-driver` to `ebs-csi-controller-sa`
ebs-csi plugin expects a specific service account name as mentioned here - https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
=> docs: Correct EKS IRSA example to use the correct service account name for the Amazon EBS CSI driver

.pre-commit-config.yaml, modules/iam-role-for-service-accounts-eks/policies.tf
- Add additional Karpenter permissions for [spot pricing improvements](https://github.com/tzneal/karpenter/blob/main/website/content/en/preview/upgrade-guide/_index.md#upgrading-to-v0130)
- Changes in v0.13.0 release have added additional permission requirements 
- No
=> feat: Add additional Karpenter permissions for spot pricing improvements

.pre-commit-config.yaml, modules/iam-role-for-service-accounts-eks/policies.tf
- Add additional permission for `karpenter` IAM policy added in v0.14.0 release, which allows the use of custom AMIs without the need for an entire launch template
- Support additional permission required in v0.14.0 https://karpenter.sh/v0.14.0/upgrade-guide/#upgrading-to-v0140
=> feat: Add additional permission for `karpenter` IAM policy added in v0.14.0 release

modules/iam-user/README.md, modules/iam-user/outputs.tf
Add the way to expose encrypted ses_smtp_password_v4 in output.
Currently `iam_access_key_ses_smtp_password_v4` is empty if entity encrypted with pgp key.
The way to expose an encrypted ses_smtp_password_v4 was introduced in https://github.com/hashicorp/terraform-provider-aws/pull/19579
Most likely not
=> fix: Correct encrypted ses_smtp_password_v4 output

modules/iam-user/outputs.tf
Closes https://github.com/terraform-aws-modules/terraform-aws-iam/issues/274
=> fix: Fixed iam-user module when `encrypted_ses_smtp_password_v4` is `null`

examples/iam-assumable-role/main.tf, modules/iam-assumable-role-with-oidc/README.md, modules/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role-with-oidc/variables.tf, modules/iam-assumable-role-with-saml/README.md, modules/iam-assumable-role-with-saml/main.tf, modules/iam-assumable-role-with-saml/variables.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-role/variables.tf, modules/iam-assumable-roles-with-saml/README.md, modules/iam-assumable-roles-with-saml/main.tf, modules/iam-assumable-roles-with-saml/variables.tf, modules/iam-assumable-roles/README.md, modules/iam-assumable-roles/main.tf, modules/iam-assumable-roles/variables.tf, modules/iam-eks-role/README.md, modules/iam-eks-role/main.tf, modules/iam-eks-role/variables.tf, modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/policies.tf, modules/iam-role-for-service-accounts-eks/variables.tf
- Add support for roles created to explicitly assume their own role if desired
- Allows for users to continue using the previous default behavior https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/ if they so choose
- Closes #278
- No
=> feat: Add support for roles created to explicitly assume their own role if desired

modules/iam-role-for-service-accounts-eks/policies.tf
Added additional policies required for targetgroup binding only to work with AWS LBC
Adds two additional policies to the subset of policies that are in effect when only using TargetGroupBinding policies with the AWS Load Balancer Controller.
The policies applied when using only `var.attach_load_balancer_controller_targetgroup_binding_only_policy = true`
is not sufficient for target group binding to work in latest version of AWS LBC. Not sure when the issue arose, and it may be related to how I define inline ingresses. Nonetheless I am only using TargetGroupBinding resources and the policy fails for that use case. More details described here: [issue](https://github.com/terraform-aws-modules/terraform-aws-iam/issues/291)
This doesn't break backwards compatibility
=> fix: Added additional policies required for targetgroup binding only to work 

modules/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role-with-saml/main.tf, modules/iam-group-with-policies/main.tf, modules/iam-group-with-policies/policies.tf, modules/iam-read-only-policy/main.tf
- Correct tflint errors for latest version of tflint
- Resolves tflint `Warning: List items should be accessed using square brackets (terraform_deprecated_index)`
- No
=> fix: Correct tflint errors for latest version of tflint

modules/iam-role-for-service-accounts-eks/policies.tf
Fixes an issue where the policy was not sufficient if you use security group ids in the Karpenter `AWSNodeTemplate` instead of relying on discovery tags. Then the security groups weren't tagged, which led to insufficient permissions for Karpenter to launch the node.
Removes the need for the security group to be tagged with the Karpenter discovery tag
for Karpenter to be able to use it when launching an instance.
- Resolves #295 
If we create an AWSNodeTemplate like this:
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
name: default
spec:
subnetSelector:
aws-ids: subnet-abc,subnet-xyz
securityGroupSelector:
aws-ids: sg-abc,sg-xyz
tags:
karpenter.sh/discovery/foo-cluster: foo-cluster
```
which is perfectly valid according to Karpenter docs, we will not
be able …
=> fix: Insufficient permissions for karpenter policy when not using karpenter discovery tags on security group

CHANGELOG.md, examples/iam-assumable-role-with-oidc/README.md, examples/iam-assumable-role-with-oidc/main.tf, examples/iam-assumable-role-with-saml/README.md, examples/iam-assumable-role-with-saml/main.tf, examples/iam-assumable-roles-with-saml/README.md, examples/iam-assumable-roles-with-saml/main.tf, examples/iam-assumable-roles/README.md, examples/iam-assumable-roles/main.tf, examples/iam-eks-role/README.md, examples/iam-eks-role/main.tf, modules/iam-assumable-role-with-oidc/main.tf, modules/iam-assumable-role-with-saml/README.md, modules/iam-assumable-role-with-saml/main.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/main.tf, modules/iam-assumable-roles-with-saml/README.md, modules/iam-assumable-roles-with-saml/main.tf, modules/iam-assumable-roles/README.md, modules/iam-assumable-roles/main.tf, modules/iam-eks-role/main.tf
=> fix: Add missing locals in iam-assumable-role module

modules/iam-eks-role/README.md
Improve docs for iam-eks-role - inform user that this sub module will not work for multiple regions
Will help save time if the end user has a multi region setup. This module doesn't support creating a role for multiple EKS clusters in more than 1 region.
None
Docs change for clarity
projects
=> docs: Inform multiple region support not an option for iam-role-eks

modules/iam-role-for-service-accounts-eks/policies.tf
External secrets uses ListSecrets when searching for secrets by tag.
https://github.com/external-secrets/external-secrets/issues/1443
Add `secretsmanager:ListSecrets` to external-secrets policy.
Allows external secrets controller list all secrets when searching for secrets by tag.
No breaking changes.
I tested it by manually updating the policy in AWS.
Before updating it:
```
{"level":"error","ts":1667943642.1480799,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"test/linkinbio-api","SecretStore":"test/later-test-store","error":"AccessDeniedException: User: arn:aws:sts::795986403160:assumed-role/ExternalSecretStore20221107234613050800000003/external-secrets-provider-aws is not authorized to perform: secretsmanager:ListSecrets because …
```
=> fix: Add `secretsmanager:ListSecrets` to `external-secrets` policy

README.md, examples/iam-github-oidc/README.md, examples/iam-github-oidc/main.tf, examples/iam-github-oidc/outputs.tf, examples/iam-github-oidc/versions.tf, modules/iam-github-oidc-provider/README.md, modules/iam-github-oidc-provider/main.tf, modules/iam-github-oidc-provider/outputs.tf, modules/iam-github-oidc-provider/variables.tf, modules/iam-github-oidc-provider/versions.tf, modules/iam-github-oidc-role/README.md, modules/iam-github-oidc-role/main.tf, modules/iam-github-oidc-role/outputs.tf, modules/iam-github-oidc-role/variables.tf, modules/iam-github-oidc-role/versions.tf
- Add support for creating IAM GitHub OIDC provider and role(s)
- The two additional sub-modules allow users to setup an IAM GitHub OIDC provider plus roles that will trust this provider. This is commonly used in things like GitHub action workflows without the need for static credentials
- No
=> feat: Add support for creating IAM GitHub OIDC provider and role(s)

examples/iam-github-oidc/main.tf, modules/iam-github-oidc-role/main.tf
- Ensure that GitHub OIDC subject prefixes are normalied for `repo:`
- All of the `subjects` used in the `iam-github-oidc-role` will need to start with `repo:` so the code originally added that for users. However, nearly all documentation shows the subject with `repo:...` and users add this text into their subjects. This results in subjects that then look like `repo:repo:...` which is incorrect. This change normalizes the text to ensure that subjects only start with `repo:...` regardless of whether the user adds it or not in their provided subjects
- No
=> feat: Ensure that GitHub OIDC subject prefixes are normalied for `repo:`

.pre-commit-config.yaml, modules/iam-role-for-service-accounts-eks/policies.tf
https://docs.aws.amazon.com/systems-manager/latest/userguide/integrating_csi_driver.html#integrating_csi_driver_access
according to documentation ssm:GetParameters permission is required
atm AWS CSI Secret Store Driver failed to get parameter with error
`MountVolume.SetUp failed for volume "volume_name" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod namespace/pod-647dbc98b4-h8kl4, err: rpc error: code = Unknown desc = Failed fetching parameters: WebIdentityErr: failed to retrieve credentials caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity status code: 403, request id: request-uuid`
-
- use https://github.com/aws/secrets-store-csi-driver-provider-aws
- `attach_external_secrets_policy  = true`; …
=> fix: Add `ssm:GetParameters` permission to `external-secrets` policy

examples/iam-assumable-role/main.tf, modules/iam-assumable-role/README.md, modules/iam-assumable-role/variables.tf
`role_name` conflicts with `role_name_prefix` in the `iam-assumable-role` module. 
https://github.com/terraform-aws-modules/terraform-aws-iam/issues/318
No.
=> fix: Update `role_name` default to `null`

modules/iam-assumable-role-with-saml/README.md, modules/iam-assumable-role-with-saml/main.tf, modules/iam-assumable-role-with-saml/variables.tf
Added the abbility to append optional extra trusted roles actions appart from the default "AssumeRoleWithSAML" in the iam-assumable-role-with-saml module
Wanted the to utilize the module to avoid rewiting all the logic from scratch but also have the ability to add some extra actions that apply to our use cases.
None as far as I know.
Internally in our organisation in many deployments. Unable to showcase.
=> feat: Added Extra STS actions param in assumable role with SAML

modules/iam-group-with-policies/policies.tf
Fix the `IAMSelfManagement` policy to allow virtual MFA devices creation.
Due to [this new feature](https://aws.amazon.com/blogs/security/you-can-now-assign-multiple-mfa-devices-in-iam/), the resource name of virtual MFA devices change and the policy doesn't work anymore. 
The wildcard in the MFA resource name is required now, because the user must specify a name for his virtual MFA device, and this is a part of the resource name.
- Resolves #312
=> feat: Allow multiple MFA devices and users to manage MFA devices

modules/iam-role-for-service-accounts-eks/policies.tf
modules/iam-role-for-service-accounts-eks -
EBS-CSI driver policy - fix condition string for DeleteVolume action to reflect the changes in the upstream
Issue - https://github.com/terraform-aws-modules/terraform-aws-iam/issues/325
The change in the upstream - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1450
There are no breaking changes
- tested on the EKS 1.23, Chart: aws-ebs-csi-driver-2.11.1, the driver version: 1.11.3
=> fix: Reflect the changes in the ebs_csi driver

modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/policies.tf
Add `eks:DescribeCluster` for Karpenter IRSA role
This is needed as of Karpenter 0.25: https://github.com/aws/karpenter/issues/3462
- Closes #341 
No
I tested on my local setup.
=> feat: Add `eks:DescribeCluster` for Karpenter cluster endpoint auto discovery

modules/iam-group-with-assumable-roles-policy/README.md, modules/iam-group-with-assumable-roles-policy/main.tf, modules/iam-group-with-assumable-roles-policy/variables.tf
Add a new input variable to specify IAM path in `iam-group-with-assumable-roles-policy`, fixing #344 
Adds the feature requested in #344 while keeping full backwards compatibility
None
=> feat: Add support for `path` in `iam-group-with-assumable-roles-policy`

modules/iam-role-for-service-accounts-eks/README.md
Updates the URL for the Karpenter Cloudformation file which contains the IAM permissions
Karpenter changed the directory structure in their repo, so the old link was broken
None
=> docs: Update cloudformation.yaml link for Karpenter IAM

modules/iam-role-for-service-accounts-eks/policies.tf
Just like ListSecrets from Secrets Manager the DecribeParameter action is always required to allow full access
With out this the policy will not work when using the external_secrets_ssm_parameter_arns variable
no
=> fix: DescribeParameter always needs full access

modules/iam-role-for-service-accounts-eks/policies.tf
Add elasticloadbalancing:AddTags permissions to AWS Load Balancer Controller policy required for version 2.4.7
Version 2.4.7 of AWS ALB controller has been released with an updated IAM permission https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.4.7.
The permission required is elasticloadbalancing:AddTags. See change here https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3046/files.
Updates AWS ALB Controller policy to match latest on version 2.4.7.
None.
I have applied the IAM policy to AWS using Terraform, then copied the resulting JSON file from AWS, and did a file side-by-side comparison with the official IAM policy JSON confirming it matches.
Fixes #339
=> feat: Add `elasticloadbalancing:AddTags` permissions to AWS Load Balancer Controller policy required for version 2.4.7+

examples/iam-policy/main.tf, modules/iam-policy/README.md, modules/iam-policy/main.tf, modules/iam-policy/variables.tf, modules/iam-read-only-policy/README.md, modules/iam-read-only-policy/main.tf, modules/iam-read-only-policy/variables.tf
Fixes https://github.com/terraform-aws-modules/terraform-aws-iam/issues/365
Fixes https://github.com/terraform-aws-modules/terraform-aws-iam/issues/365
No.
=> feat: Add `name_prefix` to iam-policy and iam-read-only-policy modules

modules/iam-role-for-service-accounts-eks/policies.tf
Remove unnecessary action ("autoscaling:UpdateAutoScalingGroup") from the IAM policy of the Cluster Autoscaler.
Update the order of the IAM actions as in the [documentation,](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#full-cluster-autoscaler-features-policy-recommended) so that it is easier for future comparison.
Reduces the IAM permissions to the required actions.
No.
=> fix: Remove `"autoscaling:UpdateAutoScalingGroup"` permission from cluster-autoscaler IRSA

examples/iam-eks-role/README.md, examples/iam-eks-role/main.tf, modules/iam-eks-role/README.md, modules/iam-eks-role/main.tf, modules/iam-eks-role/variables.tf
Fixes #366 
Sometimes we need to assign a single role to multiple service accounts or service account names are created dynamically so we might not know them in advance. It allows us to override the default `StringEquals` condition with `StringLike` and use wildcards to allow multiple service accounts to assume the same role.
No, the new variable defaults to previously hard-coded value.
=> feat(iam-eks-role): Add variable to allow change of IAM assume role condition test operator

.pre-commit-config.yaml, examples/iam-role-for-service-accounts-eks/README.md, examples/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/policies.tf, modules/iam-role-for-service-accounts-eks/variables.tf
- Add support for AWS Gateway controller (VPC Lattice) to IRSA module
- Add new variables `cluster_autoscaler_cluster_names` and `karpenter_controller_cluster_name` which shadow their current equivalents (`cluster_autoscaler_cluster_ids` and `karpenter_controller_cluster_id`). Users should now use the `cluster_name` output from the EKS module (starting in v19.x) since `cluster_id` now has a different meaning on local clusters on Outposts. This change starts to correct that behavior and align the inputs/outputs to reduce confusion but without breaking compatibility. The `_id` equivalents will be removed at the next breaking change
- Updated the VPC and EKS module versions to the latest major versions; example has been updated and validated to reflect these changes
- IRSA role and policy …
=> feat: Add support for AWS Gateway controller (VPC Lattice) to IRSA module

modules/iam-role-for-service-accounts-eks/policies.tf
As per AWS customer notifications, the `elasticloadbalancing:AddTags` permission will be required soon for anyone calling `CreateLoadBalancer` with tags:
> On June 1, 2023, we will be adding an additional layer of security to ELB ‘Create*' API calls where API callers must have explicit access to add tags in their Identity and Access Management (IAM) policy [1]. Currently, access to attach tags was implicitly granted with access to 'Create*' APIs. … We will be allowing 'Create*' API calls with the current policy to be accepted until August 30, 2023. After this date, the 'Create*' API call will fail and return an error if the the attribute is specified and permission is not granted.
=> feat: Explicitly grant `elasticloadbalancing:AddTags` permission 

modules/iam-role-for-service-accounts-eks/policies.tf
When using the `--aws-zone-tags` filter feature of external-dns, `route53:ListTagsForResource` permissions are required.
Without it, external-dns will fail to start.
This change adds the necessary permissions required for external-dns to start when using the `--aws-zone-tags` filter.
No breaking changes.
=> feat: Added permissions to list zone tags in iam-role-for-service-accounts-eks module

examples/iam-github-oidc/main.tf, modules/iam-github-oidc-provider/README.md, modules/iam-github-oidc-provider/main.tf, modules/iam-github-oidc-provider/variables.tf, wrappers/iam-github-oidc-provider/main.tf
Add additional thumbprint list as needed. 
- Resolves #400
No.
=> feat: Github OIDC add extra thumbprints as needed

modules/iam-assumable-role/main.tf
For `iam-assumable-role` the setting `role_requires_session_name = true` is ignored when `role_requires_mfa = false`.
For the case when MFA is not enforced, the option to set the condition `role_session_name` when assuming a role is missing. This was probably due to the confusion caused by unnecessary code duplication (two separate policies whether MFA is enabled or not) when the feature was implemented.
No.
=> fix: Add missing condition role_session_name when assuming a role

modules/iam-role-for-service-accounts-eks/policies.tf
Initial set of permissions (#414) was not sufficient. Checked the [source code](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/secretsmanager/secretsmanager.go) of the secrets manager implementation of external-secrets and added remaining permissions.
There were errors on certain use cases, such as a secret changes and needs to be pushed again.
No
=> fix: Expand Permissions for external-secrets IRSA Policy towards AWS Secrets Manager

modules/iam-group-with-policies/policies.tf
The "AWS: Self-manage credentials with MFA (My security credentials)" reference policy got updated by AWS in the docs[1] and this implements the following correction:
The AllowManageOwnAccessKeys statement allows the user to create, update, and delete their own access keys.
**The user can also retrieve information about when the specified access key was last used.**
1. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html
Having the self-management policy up to date with AWS recommendations. 
None.
=> fix: Update AllowManageOwnAccessKeys statement

modules/iam-group-with-policies/policies.tf
This PR corrects IAM Self-manage policy according to example from [AWS: Allows MFA-authenticated IAM users to manage their own credentials on the My security credentials page ](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html):
1. Previously, it did not allow users to change their password on their own user page. To allow this, now the `iam:GetLoginProfile` and `iam:UpdateLoginProfile` actions to be added to the `AllowManageOwnPasswords` statement.
2. The `DenyAllExceptListedIfNoMFA` statement has been corrected to include missing ` iam:GetMFADevice` permission for own MFA management.
3. Also, in the same statement `iam:ChangePassword` action should not be allowed without MFA authorization if it was enforced. This does not …
=> feat: Allow users to change own password in iam-group-with-policies module

modules/iam-github-oidc-role/README.md, modules/iam-github-oidc-role/versions.tf
As in title
This module unnecessarily depends on the `tls` provider, I believe this copied over from `iam-github-oidc-provider`
N/A
=> fix: Remove unused TLS provider in `iam-github-oidc-role` 

modules/iam-role-for-service-accounts-eks/README.md, modules/iam-role-for-service-accounts-eks/main.tf, modules/iam-role-for-service-accounts-eks/variables.tf
The `provider` attribute is never accessed and thus shouldn't be listed. It also changes the type of `oidc_providers` from `any` to a `map(any)` because it is a map.
It clutters the requirements for the variable and thus should be removed
If someone used to pass something into `oidc_providers` it will now throw an error at an earlier stage of validation
=> docs: Remove the invalid `provider` argument from the `oidc_providers` variable description

modules/iam-role-for-service-accounts-eks/policies.tf
Closes #457
A new feature was added to [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) in v2.7.0: [mutual TLS authentication support for Ingress](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3532).
This feature requires a new IAM policy permission: `elasticloadbalancing:DescribeTrustStores`.
=> feat: Support new mTLS feature in awslb IAM policy

modules/iam-group-with-policies/policies.tf
This PR fixes default IAM permissions for user group created by `iam-group-with-policies` module, extending it to allow users set and read own access keys description when creating them via AWS Console.
The issue with missing permissions was already addressed before by PR #287 , but the lines looks like were just lost after some major changes.
None.
By applying the change to existing policies and checking AWS console.
=> feat: Allow users to set and read own access keys description (iam-group-with-policies)

.github/workflows/lock.yml, .github/workflows/pr-title.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/stale-actions.yaml, .pre-commit-config.yaml, examples/iam-group-complete/README.md, examples/iam-group-complete/versions.tf
- Update CI workflow versions to remove deprecated runtime warnings
- Updates our workflows to use the latest versions
- Removes the `deprecated runtime` warnings from the workflow execution output
- No
=> fix: Update CI workflow versions to remove deprecated runtime warnings

modules/iam-group-with-policies/policies.tf
This allows a user to change their own password when no MFA is present on the account. This is only needed in once situation: when a new users signs in, and is then forced to choose a new password. The MFA isn't set up at that point, and the changing of the password is blocked.
Currently users created with the iam_user and iam_group_with_policies are not able to sign in.
- Resolves #471 
Don't think so
I tested this manually using a new account
=> fix: Allow user to change own password when no MFA is present

modules/iam-role-for-service-accounts-eks/policies.tf
Remove a duplicate line
Found a duplicate line, does not affect anything but readability.
None
Implemented this change in my AWS IAM Policy with no issues (line is a duplicate).
=> fix: Remove duplicate API permission for Karpenter IRSA policy

modules/iam-role-for-service-accounts-eks/policies.tf
Add addition policy to enable fast snapshot restore for ebs csi
refer to this link for the details
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/fast-snapshot-restores.md
=> feat: EBS fast snapshot restores persmission for EKS IRSA

modules/iam-role-for-service-accounts-eks/policies.tf
Update VPC CNI policy to version released on 3/4/24. https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEKS_CNI_Policy.html
The VPC CNI policy is missing `ec2:DescribeSubnets ` from the updated policy.
The AWS managed VPC CNI 1.18.0 uses ec2:DescribeSubnets.
Updates VPC CNI policy.
Open issue: https://github.com/terraform-aws-modules/terraform-aws-iam/issues/474
- I have tested with a local project. This is the Terraform plan. It shows `ec2:DescribeSubnets` being added.
```
~ resource "aws_iam_policy" "vpc_cni" {
id          = "arn:aws:iam::<redacted>:policy/AmazonEKS_CNI_Policy-20240117193907447200000001"
name        = "AmazonEKS_CNI_Policy-20240117193907447200000001"
~ policy      = jsonencode(
~ {
~ Statement = [
~ {
~ Action   = [
"ec2:DescribeTags",
+ …
```
=> feat: Update VPC CNI policy to 3/4/24

modules/iam-github-oidc-role/main.tf
Correcting this to use HTTPS.  Adding a pull request to remediate a potential security issue within the "terraform-aws-modules/iam/aws//modules/iam-github-oidc-role" module that pertains to the configuration of IAM roles for OIDC (OpenID Connect) with GitHub Actions.
Issue Description:
The current implementation of the IAM role's trust relationship within the module uses an HTTP URL (http://token.actions.githubusercontent.com) in the token.actions.githubusercontent.com:iss condition. This configuration poses a security risk as the HTTP protocol is not encrypted, making it susceptible to man-in-the-middle attacks where an attacker could intercept or alter the communication.
Security Risk:
Using HTTP allows potential attackers to intercept the authentication tokens used between GitHub …
=> fix: Fixed trust condition in modules/iam-github-oidc-role to be https

modules/iam-github-oidc-role/main.tf
We are in need of having the enterprise suffix in our github oidc. This change should allow us to use the terraform-aws-iam submodule with ease.
There are github users which use the enterprise path in the github issuer field.
=> feat: Allow changing iss for the github oidc role

modules/iam-github-oidc-role/README.md, modules/iam-github-oidc-role/main.tf, modules/iam-github-oidc-role/variables.tf, wrappers/iam-github-oidc-role/main.tf
- Allow modifying the `iam-github-oidc-role` subject condition
- Resolves #522
=> feat: Allow modifying the `iam-github-oidc-role` subject condition

modules/iam-role-for-service-accounts-eks/policies.tf
This PR is to update the iam-role-for-service-accounts-eks module to add additional permissions when attach_load_balancer_controller_policy is set to true.
Addresses https://github.com/terraform-aws-modules/terraform-aws-iam/issues/524.  Stems from upstream updates to https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json that have not yet been ported into this module.
Resolves #524 
None
- [ x ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ x ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [ x ] I have executed `pre-commit run -a` on my pull request
=> feat: Update IAM policy for AWS Load Balancer Controller to support Listener Attributes

modules/iam-role-for-service-accounts-eks/policies.tf
Update to the EBS CSI Driver IAM Policy
See details at https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2190
Copied changes from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2163
=> feat: Update AWS EBS CSI Driver IAM Policy

modules/iam-role-for-service-accounts-eks/policies.tf
Add functionality to interpolate resource arns to use local.partition instead of hardcoded value of "aws" to prevent breaking non-commercial use cases.
Updated previously changed values to use local.partition instead of hardcoded 'aws' reference.
Resolves #531 
This shouldn't be a breaking change and is using a pattern that exists other places in the policies.tf file.
Tested with project that was previously broken by a previous update to validate fix.
Ran
=> fix: Use dynamic partition value

modules/iam-role-for-service-accounts-eks/README.md
Mountpoint S3 CSI Driver was added to the list of optional supported policies in the Readme. 
The policy already exists but is not in the documentation. Only in the list of inputs is the Mountpoint S3 CSI Driver described in the readme. This prevents the assumption that the Mountpoint S3 CSI Driver policy is not supported.
=> docs: Add Mountpoint S3 CSI Driver to the list of optional supported policies for IRSA role

modules/iam-role-for-service-accounts-eks/policies.tf
Update to the AWS Load Balancer Controller Policy
See details at kubernetes-sigs/aws-load-balancer-controller#3921
=> feat: Add `ec2:GetSecurityGroupsForVpc` for AWS LB Controller `v2.10.0`

modules/iam-role-for-service-accounts-eks/policies.tf
This pull request includes a change to the IAM policy document for external secrets in the `modules/iam-role-for-service-accounts-eks/policies.tf` file. The change adds a new permission to the policy.
* Added `secretsmanager:BatchGetSecretValue` permission to the `data "aws_iam_policy_document" "external_secrets"` block to allow batch retrieval of secret values.
External Secrets 0.12.1 introduces the use of BulkFetch to fetch secrets from the AWS Secret Manager.
https://github.com/external-secrets/external-secrets/releases
https://github.com/external-secrets/external-secrets/blob/main/docs/provider/aws-secrets-manager.md?plain=1
No breaking changes
=> feat: Update policie for External Secrets 0.12.1

modules/iam-role-for-service-accounts-eks/policies.tf
See https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.11.0
> We've updated the reference IAM policies to explicitly add the elasticloadbalancing:DescribeCapacityReservation and elasticloadbalancing:ModifyCapacityReservation permissions for describing and modifying capacity reservation. Please be sure to apply the latest IAM policy when upgrading.
=> feat: Add policies for AWS LBC v2.11.0

modules/iam-read-only-policy/main.tf
`docker pull` does API request to ECR and requires [BatchGetImage](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_BatchGetImage.html). With Read Only policy we expect that we can pull image from the registry.  
This PR adds `BatchGet*` action to address this problem.
=> feat: Add `BatchGet*` to IAM read only policy

modules/iam-assumable-role/main.tf
Change `coalesece` to `coalesce` 
`coalesece` is a non existing method in terraform so all inline policies are named `_inline_`
None
=> fix: Fix creation of inline polices

modules/iam-role-for-service-accounts-eks/policies.tf
This pull request includes updates to the IAM policy document for external secrets in the `modules/iam-role-for-service-accounts-eks/policies.tf` file. The changes adjust the actions allowed for the secrets manager.
Changes to IAM policy document:
* Added the `secretsmanager:BatchGetSecretValue` action to the list of allowed actions in one statement.
* Removed the `secretsmanager:BatchGetSecretValue` action from another statement to avoid redundancy.
Two weeks ago, the `0.12.1`  version was launched for external-secrets. The new version requires a new permission for the action  `BatchGetSecretValue`.
I opened this PR  https://github.com/terraform-aws-modules/terraform-aws-iam/pull/542  with the suggested changes from the external-secrets repo, and the proposed policy was not working as …
=> fix: Fix IAM policy for External Secrets

modules/iam-role-for-service-accounts-eks/policies.tf
Latest release of AWS LBC (v2.12.x) adds support of intergrating AWS VPC IPAM
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.12.0
latest IAM Policy for AWS LBC: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json
No.
=> feat: Update IAM permissions for load balancer controller v2.12.0

modules/iam-role-for-service-accounts-eks/policies.tf
IAM policy for External-DNS has changed.
`route53:ListTagsForResource` => `route53:ListTagsForResource`**s**
See https://github.com/kubernetes-sigs/external-dns/commit/658d1efb76d7ce1f454cec9e8e92192c6c19d6fb
The policy does not work with recent external-dns version. It aligns the policy with the doc
The policy will not work with older version. We could provide backward compatibility by either providing both actions `ListTagsForResources` and `ListTagsForResource`, or a toggle.
=> fix: IAM policy for External-DNS policy

.pre-commit-config.yaml, modules/iam-role-for-service-accounts-eks/policies.tf
Latest release of AWS LBC (v2.13.x) adds this permission `ec2:DescribeRouteTables`
latest IAM Policy for AWS LBC: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json
No.
- Tested using my fork:
```
module "aws_load_balancer_controller_irsa" {
source = "git::https://github.com/RafiGreenberg/terraform-aws-iam//modules/iam-role-for-service-accounts-eks"
role_name = "aws-load-balancer-controller"
attach_load_balancer_controller_policy = true
oidc_providers = {
main = {
provider_arn               = module.eks.oidc_provider_arn
namespace_service_accounts = ["kube-system:aws-load-balancer-controller"]
}
}
}
```
- Plan:
```
$ tf plan
~ resource "aws_iam_policy" "load_balancer_controller" {
id               = …
```
=> feat: Update AWS Load Balancer controller policy to match v2.13 of the upstream project

.pre-commit-config.yaml, examples/iam-eks-role/README.md, examples/iam-eks-role/versions.tf, examples/iam-role-for-service-accounts-eks/README.md, examples/iam-role-for-service-accounts-eks/versions.tf, modules/iam-role-for-service-accounts-eks/policies.tf
This PR removes the unnecessary `condition` block from the `ebs_csi` IAM policy document.
According to AWS documentation, this `condition` is not required and may cause permission issues when using the EBS CSI driver with IRSA.
Closes #562
- AWS Docs: [EBS CSI IAM Policy](https://docs.aws.amazon.com/...)
No impact on functionality. Simplifies the policy and aligns with AWS recommendations.
=> feat: Update EBS CSI IAM policy to match current upstream project

modules/iam-role-for-service-accounts/main.tf, modules/iam-user/README.md, modules/iam-user/main.tf
- Add default IRSA policy name for canned policies if a more specific name is not provided
- Fix incorrect policy attachment for `iam-user`
- Resolves #593
- No
=> feat: Add default IRSA policy name, fix incorrect policy attachment for `iam-user`

modules/iam-oidc-provider/README.md, modules/iam-oidc-provider/variables.tf
=> docs: Correct typo on documentation

modules/iam-role/main.tf
- Adding a check for local.bitbucket_provider to check for provider url only when enable_bitbucket_oidc is enabled.
- Fix for issue  https://github.com/terraform-aws-modules/terraform-aws-iam/issues/604
In the 6.x version of the module, when oidc_provider_urls has multiple provider urls a bitbucket check fails and prevents plan for other generic providers as well.
=> fix: Modify BitBucket provider URL extraction to be more robust when none or multiple URLs are provided
