terraform-aws-modules/terraform-aws-iam

- modules/iam-assumable-roles/main.tf
- modules/iam-assumable-roles/outputs.tf
This allows the advertised variables to function.
The outputs had to be modified to work with conditionals in line with
the workaround in https://github.com/hashicorp/terraform/issues/17425.
> Implement conditional logic for role creation in iam-assumable-roles

- modules/iam-assumable-roles/main.tf
- modules/iam-assumable-roles/variables.tf
Support for longer STS sessions
https://aws.amazon.com/about-aws/whats-new/2018/03/longer-role-sessions/
> Custom Session Duration

- modules/iam-assumable-roles/README.md
- modules/iam-assumable-roles/main.tf
- modules/iam-assumable-roles/variables.tf
- modules/iam-user/README.md
- modules/iam-user/main.tf
- modules/iam-user/variables.tf
This PR adds support for policy boundary attached to role or user.
You can find reference to this feature in docs 
https://www.terraform.io/docs/providers/aws/r/iam_user.html
https://www.terraform.io/docs/providers/aws/d/iam_role.html
> Permission boundary

- README.md
- examples/iam-policy/README.md
- examples/iam-policy/main.tf
- examples/iam-policy/outputs.tf
- examples/iam-policy/policy.tpl
- modules/iam-policy/README.md
- modules/iam-policy/main.tf
- modules/iam-policy/outputs.tf
- modules/iam-policy/variables.tf
- Added IAM Policy module
- Added IAM Policy examples
> Added iam policy module

- README.md
- examples/iam-assumable-role/README.md
- examples/iam-assumable-role/main.tf
- examples/iam-assumable-role/outputs.tf
- examples/iam-group-with-assumable-roles-policy/README.md
- examples/iam-group-with-assumable-roles-policy/main.tf
- examples/iam-group-with-assumable-roles-policy/outputs.tf
- examples/iam-user/README.md
- examples/iam-user/main.tf
- examples/iam-user/outputs.tf
- modules/iam-assumable-role/README.md
- modules/iam-assumable-role/main.tf
- modules/iam-assumable-role/outputs.tf
- modules/iam-assumable-role/variables.tf
- modules/iam-assumable-roles/README.md
- modules/iam-assumable-roles/variables.tf
- modules/iam-group-with-assumable-roles-policy/README.md
- modules/iam-group-with-assumable-roles-policy/main.tf
- modules/iam-group-with-assumable-roles-policy/outputs.tf
- modules/iam-group-with-assumable-roles-policy/variables.tf
- modules/iam-user/README.md
- modules/iam-user/main.tf
- modules/iam-user/outputs.tf
> Added iam-group-with-assumable-roles-policy and iam-assumable-role

- README.md
- examples/iam-assumable-roles-with-saml/README.md
- examples/iam-assumable-roles-with-saml/main.tf
- examples/iam-assumable-roles-with-saml/outputs.tf
- modules/iam-assumable-roles-with-saml/README.md
- modules/iam-assumable-roles-with-saml/main.tf
- modules/iam-assumable-roles-with-saml/outputs.tf
- modules/iam-assumable-roles-with-saml/variables.tf
Module for creating roles for users with SAML Identity Provider like, azure, okta, itp.
> assumable roles for Users with SAML Identity Provider 

- examples/iam-assumable-roles-with-saml/README.md
- examples/iam-assumable-roles-with-saml/main.tf
- examples/iam-assumable-roles/main.tf
- modules/iam-assumable-roles-with-saml/README.md
- modules/iam-assumable-roles-with-saml/main.tf
- modules/iam-assumable-roles-with-saml/variables.tf
- modules/iam-assumable-roles/README.md
- modules/iam-assumable-roles/main.tf
- modules/iam-assumable-roles/variables.tf
> Added support for list of policies to attach to roles

- modules/iam-assumable-role/README.md
> style: Fix typo

- README.md
Fix wrong module source
For next me.
nothing
1. Copy now module example to our module.
1. `terraform plan` fails
1. Fix source
1. `terraform apply` ok
> fix: module source and name in README

- modules/iam-account/README.md
- modules/iam-account/versions.tf
- modules/iam-assumable-role-with-oidc/README.md
- modules/iam-assumable-role-with-oidc/versions.tf
- modules/iam-assumable-role/README.md
- modules/iam-assumable-role/versions.tf
- modules/iam-assumable-roles-with-saml/README.md
- modules/iam-assumable-roles-with-saml/versions.tf
- modules/iam-assumable-roles/README.md
- modules/iam-assumable-roles/versions.tf
- modules/iam-group-with-assumable-roles-policy/README.md
- modules/iam-group-with-assumable-roles-policy/versions.tf
- modules/iam-group-with-policies/README.md
- modules/iam-group-with-policies/versions.tf
- modules/iam-policy/README.md
- modules/iam-policy/versions.tf
- modules/iam-user/README.md
- modules/iam-user/versions.tf
> feat: Support for Terraform v0.13 and AWS provider v3

- examples/iam-assumable-role-with-oidc/main.tf
- modules/iam-assumable-role-with-oidc/README.md
- modules/iam-assumable-role-with-oidc/main.tf
- modules/iam-assumable-role-with-oidc/variables.tf
> feat: modules/iam-assumable-role-with-oidc: Support multiple provider URLs

- modules/iam-group-with-policies/policies.tf
Support non default partition like gov
Closes #79
No
Don't have govcloud access. Similar to #83
> fix: allow running on non-default-partition

- examples/iam-assumable-role/main.tf
- modules/iam-assumable-role/README.md
- modules/iam-assumable-role/main.tf
- modules/iam-assumable-role/variables.tf
> feat: Fixed number of policies everywhere

- examples/iam-user/outputs.tf
- modules/iam-assumable-role/main.tf
- modules/iam-user/outputs.tf
> fix: Set sensitive=true for sensitive outputs and use tolist()

- examples/iam-assumable-role/main.tf
- modules/iam-assumable-role/main.tf
> feat: Support External ID with MFA in iam-assumable-role

- modules/iam-eks-role/README.md
Just fix a couple small errors in the doc
💅
> docs: Fixed a couple of typos in the docs iam-eks-role module

- examples/iam-eks-role/README.md
- examples/iam-eks-role/main.tf
- examples/iam-eks-role/versions.tf
> fix: Fixed incorrect example of iam-eks-role

- examples/iam-eks-role/README.md
- examples/iam-eks-role/versions.tf
- examples/iam-role-for-service-accounts-eks/README.md
- examples/iam-role-for-service-accounts-eks/main.tf
- modules/iam-eks-role/main.tf
- modules/iam-eks-role/versions.tf
- modules/iam-role-for-service-accounts-eks/README.md
- modules/iam-role-for-service-accounts-eks/main.tf
- modules/iam-role-for-service-accounts-eks/policies.tf
- modules/iam-role-for-service-accounts-eks/variables.tf
- Add new addon policy for AWS load balancer controller to IRSA role
- Closes #188
- No
> feat: Add new addon policy for AWS load balancer controller to IRSA role

- examples/iam-user/README.md
- examples/iam-user/outputs.tf
- modules/iam-user/outputs.tf
> fix: Fixed output of iam_user_login_profile_password in iam-user submodule

- modules/iam-role-for-service-accounts-eks/README.md
Fixed typo in IRSA module README
Fixes annoying typo
no
I've read this line twice
> chore: Fixed typo in IRSA module README

- modules/iam-user/main.tf
Resolves #244
Works around https://github.com/hashicorp/terraform-provider-aws/issues/23567
> fix: Don't force users to reset passwords in modules/iam-user

- .pre-commit-config.yaml
- modules/iam-role-for-service-accounts-eks/policies.tf
- Add support for spot request permissions with Karpenter IRSA role
- Resolves #276 
- No
> feat: Add support for spot request permissions with Karpenter IRSA role

- examples/iam-user/README.md
- examples/iam-user/main.tf
- modules/iam-user/README.md
- modules/iam-user/main.tf
- modules/iam-user/variables.tf
Support IAM access key status. 
- Resolves #314
No.
> feat: Support IAM access key status

- modules/iam-role-for-service-accounts-eks/policies.tf
Update efs_csi policy to current version
EFS driver has updated example policy
See https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/964
no
> feat: Update efs_csi policy to support resource tagging

- modules/iam-role-for-service-accounts-eks/policies.tf
ssm:DescribeParameters is required to sync secrets from ParameterStore
Error from the external-secrets log:
aws-role is not authorized to perform: ssm:DescribeParameters on resource: * because no identity-based policy allows the ssm:DescribeParameters action\n\tstatus code: 400, request id: ff","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/e │
When using AWS System Manager Parameters with external-secrets(ESO) the secrets can not be synced unless the AWS Role that is mapped to the EKS Service Account has the ssm:DescribeParameters action.
1. Using the module: `"terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"`
2. provider: aws
3. ESO SecretStore with 
```
spec:
provider:
aws:
service: ParameterStore
region: us-east-1
auth:
jwt: …
```
> fix: Add `ssm:DescribeParameters` permission to `external-secrets` IAM role for service account (IRSA)

- README.md
- examples/iam-role/main.tf
- examples/iam-user/main.tf
- modules/iam-role/README.md
- Correct examples
- Resolves #612
- Closes #614
- No
> docs: Correct examples

- modules/iam-role/README.md
Update (I guess) outdated documentation
Incorrect documentation, which I actually tried to use.
> docs: Correct syntax in `iam-role` example documented on README
